apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.k8s_deploy_name}}
  labels:
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        backstage.io/kubernetes-id: {{cookiecutter.component_id}}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80